dj_login_system/urls.py
from xml.etree.ElementInclude import include

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.home, name='home'),
    path('signup/', user_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/home.html"), name='logout'),
    path('criarForum/', user_views.criarForum, name='forum'),
    path('<int:forum_id>/detailForum/', user_views.detailForum, name="detail"),
    path('<int:forum_id>/detailForum/reply_form/', user_views.replyForum.as_view(), name="reply"),
    path('<int:forum_id>/detailForum/like/', user_views.like_reply, name="like"),
]

users/urls.py
# from django.urls import path

# from . import views

# # urlpatterns = [
# #     path('', views.index, name='index'),
# # ]

we-heite/urls.py
from xml.etree.ElementInclude import include

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.home, name='home'),
    path('signup/', user_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/home.html"), name='logout'),
    path('criarForum/', user_views.criarForum, name='forum'),
    path('<int:forum_id>/detailForum/', user_views.detailForum, name="detail"),
    path('<int:forum_id>/detailForum/reply_form/', user_views.replyForum.as_view(), name="reply"),
    path('<int:forum_id>/detailForum/like/', user_views.like_reply, name="like"),
    path('<int:forum_id>/detailForum/done/', user_views.done_forum, name="done"),
    path('<int:user_id>/profile/', user_views.profile, name="profile"),
    path('myDiscussions/', user_views.myDisc, name='myDiscs'),
    
]

users/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    professor = models.BooleanField()
# @receiver(post_save, sender=User)
# def update_user_profile(sender, instance, created, **kwargs):
#     try:
#         instance.profile.save()
#     except ObjectDoesNotExist:
#         Profile.objects.create(user=instance,professor=False)


class Forum(models.Model):
    autor = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    title = models.TextField(max_length=255)
    body = models.TextField(max_length=9999)
    respondida = models.ManyToManyField(User, default=None, blank=True, related_name='respondida')
    
    def __str__(self):
        return self.title

class Reply(models.Model):
    autor = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    body = models.TextField(max_length=9999)
    liked = models.ManyToManyField(User, default=None, blank=True, related_name='liked')

    def __str__(self):
        return self.body

    @property
    def num_likes(self):
        return self.liked.all().count()

LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
) 

DONE_CHOICES = (
    ('Done', 'Done'),
    ('Undone', 'Undone'),
)

class Like(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, default='Like', max_length=10)

    def str(self):
        return str(self.reply)

class Forum_done(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    value = models.CharField(choices=DONE_CHOICES, default='Undone', max_length=10)

    def str(self):
        return str(self.forum)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from .models import *


class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=50, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=120, help_text='Required. Enter a valid email address.')
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')
    professor = forms.BooleanField(required=False)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'birth_date', 'password1', 'password2', 'professor')
 

class CreateInForum(ModelForm):
    title = forms.CharField(max_length=50, required=True, help_text='Required.')
    body = forms.CharField(max_length=10000, required=True, help_text='Required.')

    class Meta:
        model = Forum
        fields = ['title', 'body']

# class CreateInReply(ModelForm):
#     body = forms.CharField(max_length=10000, required=True, help_text='Required.')

#     class Meta:
#         model = Reply
#         fields = ['body',]


# class CreateInDiscussion(ModelForm):
#     class Meta:
#         model= Disc
#         fields = "__all__"'''

users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from .forms import CreateInForum, SignupForm  # , CreateInReply,
from .models import Forum, Forum_done, Like, Reply,Profile

def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    discussao = Forum.objects.filter(title__icontains=q).order_by("-id")

    # discussao = Forum.objects.all().order_by(
    #     '-id')  # Collect all records from table


    context = {'discussao': discussao}
    return render(request, 'users/home.html', context )


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
           
            birth_date=form.cleaned_data.get('birth_date')
            professor=form.cleaned_data.get('professor')
         
            profile=Profile.objects.create(user=user,professor=professor,birth_date=birth_date)
            profile.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')            
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignupForm()

    context = {'form': form}
    return render(request, 'users/signup.html', context)


def criarForum(request):
    if request.method == 'POST':
        form = CreateInForum(request.POST)
        if form.is_valid():
            forum = form.save()
            forum.refresh_from_db()
            forum.autor = request.user
            forum.title = form.cleaned_data.get('title')
            forum.body = form.cleaned_data.get('body')
            forum.save()
            return redirect('home')
    else:
        form = CreateInForum()

    context = {'form': form}
    return render(request, 'users/formulario.html', context)

def detailForum(request, forum_id):
    forum = get_object_or_404(Forum, pk=forum_id)
    replys = Reply.objects.filter(forum=forum_id).order_by('-id')
    user = request.user  # Collect all records from table

    return render(request, "users/detailForum.html", {'forum': forum, 'replys': replys, 'user':user})


class replyForum(CreateView):
    model = Reply
    fields = ['body']
    template_name = 'users/reply_form.html'

    def form_valid(self, form):
        form.instance.autor = self.request.user
        form.instance.forum = Forum.objects.get(pk=self.kwargs['forum_id'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('detail', kwargs={'forum_id': self.kwargs['forum_id']})
    
def like_reply(request, forum_id):
    user = request.user
    if request.method == 'POST':
        reply_id = request.POST.get('reply_id')
        reply_obj = Reply.objects.get(id=reply_id)

        if user in reply_obj.liked.all():
            reply_obj.liked.remove(user)
        else:
            reply_obj.liked.add(user)

        like, created = Like.objects.get_or_create(autor=user, reply_id=reply_id) 

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
    return redirect('detail', forum_id=forum_id)

def done_forum(request, forum_id):
    user = request.user
    if request.method == 'POST':
        forum_id = request.POST.get('forum_id')
        forum_obj = Forum.objects.get(id=forum_id)

        if user in forum_obj.respondida.all():
            forum_obj.respondida.remove(user)
        else:
            forum_obj.respondida.add(user)

        forum , created = Forum_done.objects.get_or_create(autor=user, forum_id=forum_id) 

        if not created:
            if forum.value == 'Done':
                forum.value = 'Undone'
            else:
                forum.value = 'Done'
    return redirect('detail', forum_id=forum_id)

def profile(request, user_id):
    profile = get_object_or_404(User, pk=user_id)
    discussao = Forum.objects.filter(autor_id = user_id).order_by("-id")
    qtd_discussao = len(discussao)
    reply = Reply.objects.filter(autor_id = user_id).order_by("-id")
    qtd_reply = len(reply)

    return render(request, 'users/profile.html', {'profile' : profile, 'qtd_discussao' : qtd_discussao, 'qtd_reply' : qtd_reply}) 

def myDisc(request):
    user = request.user
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    discussao = Forum.objects.filter(title__icontains=q).order_by("-id")

    # discussao = Forum.objects.all().order_by(
    #     '-id')  # Collect all records from table


    context = {'discussao': discussao, 'user':user}
    return render(request, 'users/myDiscs.html', context )






        
# class replyForum(CreateView):
#     model = Reply
#     fields = ['body']

#     def form_valid(self, form):
#         form.instance.forum_id = self.kwargs.get("forum_id")
#         return super().form_valid(form)

# def replyForum(request, forum_id):
#     if request.method == 'POST':
#         form = CreateInReply(request.POST)
#         if form.is_valid():
#             reply = form.save()
#             reply.refresh_from_db()
#             reply.autor = request.user
#             reply.body = form.cleaned_data.get('body')
#             print(forum_id)
#             reply.forum = forum_id
#             reply.save()

#             forum = get_object_or_404(Forum, pk = forum_id)
#             return render(request, "users/detailForum.html", {'forum':forum})

#     else:
#         form = CreateInReply()

#     context = {'form': form}
#     return render(request, 'users/replyForum.html', context)

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>User Authentication System</title>
    <script src="https://kit.fontawesome.com/a560e25e8e.js" crossorigin="anonymous"></script>
    {% block style %}
    {% endblock style %}
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div> 
</body>
</html>

users/templates/users/detailForum.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/a560e25e8e.js" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<style>
    * {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        margin: 0px;
        padding: 0px;
    }

    body {
        display: flex;
        flex-direction: column;
        align-items: center;
        background-color: #ebebeb;
    }

    .main-content {
        margin-top: 100px;
        display: flex;
        flex-direction: column;
        align-items: center;
        width: 1200px;
        height: fit-content;
        padding: 5px;
        border-radius: 5px;
    }

    .discussion-box {
        margin-top: 0px;
        padding: 5px;
        padding-top: 0px;
        width: 1000px;
        border: 1px solid;
        margin-top: 20px;
        border-radius: 5px;
    }

    h2 {
        text-align: center;
    }

    h4 {
        background-color: yellow;
        width: fit-content;
        height: fit-content;
        font-size: 20px;
        margin: 0px;
        padding: 0px;
        display: flex;
        justify-content: start;
    }

    .below-disc {
        display: flex;
        width: 1000px;
        justify-content: space-between;
    }

    .answer-box {
        margin-top: 0px;
        padding-top: 0px;
        padding: 5px;
        width: 1000px;
        border: 1px solid;
        margin-top: 20px;
        border-radius: 5px;
    }

    .position-back-button {
        display: flex;
        width: 1000px;
        justify-content: start;
    }

    a {
        color: black;
        text-decoration: none;
    }

    h5 {
        display: flex;
        width: 1000px;
        justify-content: end;
        font-size: 20px;
    }

    .a3 {
        font-size: 30px;
        color: #ebebeb;
        text-justify: end;
        -webkit-text-stroke-width: 2px;
        -webkit-text-stroke-color: #000;
    }

    .TextBody {
        word-wrap: break-word;
        padding-bottom: 40px;
    }

    .like-function {
        display: flex;
        justify-content: space-between;
        width: 1000px;
    }

    .like {
        font-size: 30px;
        text-decoration: none;
        background: none;
        border: none;
        color: #ebebeb;
        -webkit-text-stroke-width: 2px;
        -webkit-text-stroke-color: #000;
    }

    .deslike {
        font-size: 30px;
        text-decoration: none;
        background: none;
        border: none;
        color: cyan;
        -webkit-text-stroke-width: 2px;
        -webkit-text-stroke-color: #000;
    }

    strong {
        font-size: 20px;
        width: 1000px;
        display: flex;
        justify-content: center;
        margin-left: 30px;
    }

    .statusforum {
        font-size: 20px;
    }

    button {
        margin-top: 10px;
        height: fit-content;
        width: fit-content;
        padding: 6px;
        color: #fff;
        font-weight: bolder;
        text-decoration: none;
        border: none;
        border-radius: 8px;
    }

    .prof {
        display: flex;
        height: fit-content;
        background-color: red;
        width: 1000px;

    }

    h6{
        background-color: blue;
        font-size: 20px;
        width: fit-content;
        height: fit-content;
        position: relative;
    }
    .BoxAutor {
        width: 1000px;
        height: 25px;
        background: none;
        display: flex;
        justify-content: space-between;
        padding: 3px;
        font-size: 15px;
    }
    .autor {
        font-size: 20px;
    }

    .professor {
        justify-self: center;
        font-size: 20px;
    }

    header {
        position: fixed;
        color: white;
        height: 60px;
        background-color: rgba(121, 116, 116, 1);
        display: flex;
        justify-content: center;
        width: 100vw;
        border-bottom: grey;
        border-radius: 0px 0px 5px 5px;
        box-shadow: 2px 2px 2px 1px rgba(0, 0, 0, 0.2);
    }

    h1 {
        font-size: 50px;
    }

    .a8 {
        text-decoration: none;
        color: white;
    }
</style>

<body>
    <header>
        <h1><a class="a8" href="{% url 'home' %} ">Weheite</a></h1>
    </header>
    <div class="main-content">
        <div class="BoxAutor">
            <a href="{{forum.autor_id}}/profile/" class = "autor">
                <p class="autor"><b><i>@{{forum.autor}}</i></b></p>
            </a>
            {% if forum.autor.profile.professor %}
                <p class="professor"><b>PROFESSOR</b></p>
            {% endif %}
        </div>
        <div class="discussion-box">
            <h2><b>{{forum.title}}</b></h2>
            <p>{{forum.body}}</p>
        </div>
        <div class="below-disc">
            {%if user.id == forum.autor_id %}
            <form action="{% url 'done' forum_id=forum.id %}" method='POST' class="ui form">
                {% csrf_token %}
                <input type='hidden' name='forum_id' value="{{forum.id}}" />
                <input type='hidden' name='user' value="{{user}}" />
                {% if user not in forum.respondida.all %}
                <button class="undone" type="submit" style="background-color: red;">Marcar como Resolvida</button>
                {% else %}
                <button class="done" type="submit" style="background-color: green;">Resolvida</button>
                {% endif %}
            </form>
            {% else %}
            {% if forum.autor in forum.respondida.all %}
            <div class="statusforum" style="color: green;">Resolvida<i class="fa-solid fa-check"></i></div>
            {% else %}
            <div class="statusforum" style="color: red;">Não Resolvida <i class="fa-regular fa-circle-xmark"></i></div>
            {%endif%}
            {%endif%}
            <a class="a3" href="reply_form/ "><i class="fa-solid fa-comment"></i></a>
        </div>
        {% if replys %}
        <h3>RESPOSTAS</h3>
        {% for reply in replys %}
        <div class="BoxAutor">
            <a href="{{reply.autor_id}}/profile/" class = "autor">
                <p class="autor"><b><i>@{{reply.autor}}</i></b></p>
            </a>
            {% if reply.autor.profile.professor %}
                <p class="professor"><b>PROFESSOR</b></p>
            {% endif %}
        </div>
        <div class="answer-box">
            <p class="TextBody">{{reply.body}}</p>
        </div>
        <div class="like-function">
            {% if reply.liked.all.count == 1 %}
            <strong>{{ reply.liked.all.count }} like</strong>
            {%else%}
            <strong>{{ reply.liked.all.count }} likes</strong>
            {%endif%}
            <form action="{% url 'like' forum_id=forum.id %}" method='POST' class="ui form">
                {% csrf_token %}
                <input type='hidden' name='reply_id' value="{{reply.id}}" />
                <input type='hidden' name='user' value="{{user}}" />
                {% if user not in reply.liked.all %}
                <button class="like" type="submit"><i class="fa-solid fa-thumbs-up"></i></button>
                {% else %}
                <button class="deslike" type="submit"><i class="fa-solid fa-thumbs-up"></i></button>
                {% endif %}
            </form>
        </div>
        {% endfor %}
        {%else%}
        <h3>Ainda não tem nenhuma resposta</h3>
        {% endif %}
        <div class="position-back-button">
            <a href="{% url 'home' %} "><i class="fa-solid fa-arrow-left"></i></a>
        </div>
    </div>
</body>

</html>

users/templates/users/formulario.html
{% extends 'users/base.html' %}
{% block style %}
<style>
    * {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    body {
        background-color: #ebebeb;
    }

    h1 {
        font-size: 60px;
    }

    .main-content {
        display: flex;
        flex-direction: column;
        width: 70vw;
        align-items: center;
        margin-top: 50px;
    }

    input {
        background: none;
        border-radius: 5px;
        width: 400px;
    }

    .buttons-position {
        display: flex;
        justify-content: space-between;
        width: 400px;
    }

    a {
        text-decoration: none;
        color: black;
    }

    button {
        background-color: lightcoral;
        height: fit-content;
        width: fit-content;
        padding: 6px;
        color: #fff;
        font-weight: bolder;
        text-decoration: none;
        border: none;
        border-radius: 8px;
        align-self: center;
    }

    #id_body {
        height: 200px;
        text-align: start;
        text-justify: start;
        word-wrap: break-word;
    }

    label {
        font-size: 30px;
    }
</style>
{% endblock style %}
{% block content %}
<div class="main-content">
    <h1>
        Weheite
    </h1>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
        {% endfor %}
        </p>
        {% endfor %}
        <div class="buttons-position">
            <a href="{% url 'home' %} "><i class="fa-solid fa-arrow-left"></i></a>
            <button type="submit">Enviar</button>
        </div>
    </form>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block style %}
<style>
  * {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  }

  body {
    background-color: #ebebeb;
  }

  h2 {
    font-size: 100px;
  }

  input {
    font-size: 18px;
    background: none;
    display: flex;
    width: 400px;
    height: 30px;
    border-radius: 5px;
  }

  .main-content-login {
    display: flex;
    height: 600px;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  button {
    background-color: lightcoral;
    height: fit-content;
    width: fit-content;
    padding: 6px;
    color: #fff;
    font-weight: bolder;
    text-decoration: none;
    border: none;
    border-radius: 8px;
    align-self: center;
  }

  a {
    background: none;
    color: black;
    font-size: 18px;
    text-justify: start;
    margin-right: 160px;
  }
</style>
{% endblock style %}

{% block content %}
<br>
<div class="main-content-login">
  <h2 style="text-align: center;">Login</h2>
  <br>
  <br>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <a href="{% url 'home' %} "><i class="fa-solid fa-arrow-left"></i></a>
    <button type="submit">Entrar</button>
  </form>
</div>
{% endblock content%}

users/templates/users/logout.html
{% extends 'users/base.html' %}

{% block content %}
    <br>
    <div class="alert alert-success" role="alert">
        <h2 style="text-align: center;">Logged out!</h2>
    </div>

    <h3>Login again?</h3>
    <a href="{% url 'login' %}">---> Login</a> <br>
    <a href="{% url 'home' %}"><--- Or go back to home.</a>
{% endblock content %}

users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    * {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        margin: 0px;
        padding: 0px;
    }

    body {
        align-items: center;
    }

    header {
        position: fixed;
        color: white;
        height: 60px;
        background-color: rgba(122, 116, 116, 1);
        display: flex;
        justify-content: center;
        width: 100vw;
        border-bottom: grey;
        border-radius: 0px 0px 5px 5px;
        box-shadow: 2px 2px 2px 1px rgba(0, 0, 0, 0.2);
    }

    h1 {
        font-size: 50px;
    }

    .a8 {
        text-decoration: none;
        color: white;
    }

    footer {
        height: 100vh;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;

    }

    h2 {
        font-size: 100px;
    }

    p {
        font-size: 50px;
    }
</style>
<body>
    <header>
        <h1><a class="a8" href="{% url 'home' %} ">Weheite</a></h1>
    </header>
    <footer>
        <h2>Perfil de {{profile.username}}</h2>
        {% if profile.profile.professor %}
        <p>Este usuário é um professor.</p>
    {% endif %}
        <p>Email: {{profile.email}}</p>
        <p>Criou {{qtd_discussao}} discussões </p>
        <p>Criou {{qtd_reply}} respostas </p>
        <p>Conta criada em: {{profile.date_joined}}</p>
    </footer>
    
</body>
</html>

users/templates/users/reply.html
{% extends 'users/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        </p>
        {% endfor %}
        <button type="submit">Enviar</button>
    </form>
{% endblock content %}

users/templates/users/replyForum.html
{% extends 'users/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        </p>
        {% endfor %}
        <button type="submit">Enviar</button>
    </form>
{% endblock content %}

users/templates/users/signup.html
{% extends 'users/base.html' %}

{% block style %}
<style>
    * {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    body {
        background-color: rgb(197, 193, 193);
        display: flex;
        justify-items: center;
    }

    .main-content{
        margin-top: 30px;
        display: flex;
        flex-direction: column;
    }

    h2 {
        font-size: 100px;
    }

    input {
        font-size: 18px;
        background: none;
        display: flex;
        width: 400px;
        height: 30px;
        border-radius: 5px;
    }

    button {
        background-color: lightcoral;
        height: fit-content;
        width: fit-content;
        padding: 6px;
        color: #fff;
        font-weight: bolder;
        text-decoration: none;
        border: none;
        border-radius: 8px;
        align-self: center;
    }

    a {
        background: none;
        color: black;
        font-size: 18px;
        text-justify: start;
        margin-right: 160px;
    }

    form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .signup-buttons {
        width: 400px;
        display: flex;
        justify-content: start;
    }

    #id_professor {
        background: red;
        color: red;
    }


</style>
{% endblock style %}

{% block content %}
<div class = "main-content">
    <h3 style="text-align: center;">Sign Up</h3>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                <small style="color: rgb(99, 92, 92)">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <div class="signup-buttons">
            <a href="{% url 'home' %} "><i class="fa-solid fa-arrow-left"></i></a>
            <button type="submit">Criar conta</button>
        </div>
    </form>
</div>
{% endblock content%}